name: rnaseq-voila
channels:
        - conda-forge
        - bioconda
        - plotly
dependencies:
        - dominate=2.9.1
        - jupyter_core=5.7.2
        - jupyterlab=4.1.5
        - jupyter_server=2.25.4
        - python=3.12.1
        - plotly=5.1.0
        - nbconvert=7.16.2
        - matplotlib-base
        - pandas
        - ipywidgets
        - scikit-learn
        - wheel=0.41.2
        - voila=0.5.5  
